name: Test action
on: [push, pull_request, workflow_dispatch]
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          files: examples/*.md
